#ifndef _PORT_DEFS_H_
#define _PORT_DEFS_H_
/*
 LED5 	GPIO 145
 LED4	GPIO 144
 LED3	GPIO 143
 LED2	GPIO 142
 LED1	GPIO 141

 BUZZ	GPIO 139
 CP_C	GPIO 138
 CP_T	GPIO 137
 ON_T	GPIO 135
 ACC_T	GPIO 134
 CC2_T	GPIO 133
 SD_WP	GPIO 130
 SD_CD	GPIO 129
 HEAT_IO	GPIO 128
 FS_IO	GPIO 127
 Pre-Charge_IO	GPIO 126
 Dis-charge_IO-	GPIO 125
 Dis-charge_IO+	GPIO 124
 Charge_IO	GPIO 123
 INS_CTRL_V-	GPIO 122
 INS_CTRL_V+	GPIO 121
 F_WP	GPIO 120
 PRE-CHARGE_T	GPIO 117
 CHARGE_T	GPIO 116
 DIS-CHARGE+_T	GPIO 115
 DIS-CHARGE-_T	GPIO 114
 * 
 * */
#include "driver/Gpio/gpio.h"

enum BMS_IO_PORT_DEFS
{
	IO_CTL_LED5 = 145,
	IO_CTL_LED4 = 144,//191,//
	IO_CTL_LED3 = 143,//190,//
	IO_CTL_LED2 = 142,//189,//
	IO_CTL_LED1 = 141,//188,//
	IO_CTL_PRECHARGE = 126,
	IO_CTL_DISCHARGE_NEGATIVE = 125,
	IO_CTL_DISCHARGE_POSITIVE = 124,
	IO_CTL_CHARGE = 123,
	IO_CTL_INS_CTRL_V_NEGATIVE = 122, //絕緣電阻
	IO_CTL_INS_CTRL_V_POSITIVE = 121, //劇院電阻
	IO_CTL_BUZZ = 139,
	IO_CTL_HEAT = 128,
	IO_CTL_FANS = 127,

	IO_STATUS_CP_C = 138,
	IO_STATUS_ON = 135,
	IO_STATUS_ACC = 134,
	IO_STATUS_CC2 = 133,
	IO_STATUS_PRECHARGE =114,// 117,  与硬件端口不一致，更改
	IO_STATUS_CHARGE = 115,//116,
	IO_STATUS_DISCHARGE_POSITIVE = 116,//115,
	IO_STATUS_DISCHARGE_NEGATIVE =117,// 114,
	IO_ISR_CP_T = 137,  //PWM
	IO_SD_WP = 130,
	IO_SD_CD = 129,
	IO_FRAM_WP = 120,
	/*
	 CC	ADC 5	交流充电机接口状态检测（需将检测到的电压值换算成电阻值）
	 ADC_YC	ADC 4	预充电压检测
	 ADC_CU2	ADC 3	霍尔传感器电流检测（充电）
	 ADC_CU1	ADC 2	霍尔传感器电流检测（放电）
	 INS_V-	ADC 1	绝缘电阻检测（电池组负极对地绝缘电阻）
	 INS_V+	ADC 0	绝缘电阻检测（电池组正极对地绝缘电阻）
	 */
	ADC_PORT_INS_P = 0,
	ADC_PORT_INS_N = 1,
	ADC_PORT_CURRENT_DISCHARGE = 2,
	ADC_PORT_CURRENT_CHARGE = 3,
	ADC_PORT_PRECHARGE = 4,
	ADC_PORT_ACCIN = 5,  // AC charger insert check
	/*
	 MBM_SCK	SPI GPIO102	LTC6804通讯
	 MBM_CS	SPI GPIO105	LTC6804通讯
	 MBM_MISO	SPI GPIO103	LTC6804通讯
	 MBM_MOSI	SPI GPIO104	LTC6804通讯
	 * 
	 * */
	SPIB_PORT_SCK = 102,
	SPIB_PORT_CS = 105,
	SPIB_PORT_MISO = 103,  //179     //
	SPIB_PORT_MOSI = 104,

	/*
	 PCSB4_SCK	109	SD卡和FRAM复用SPI口
	 PCSB2_MOSI	107	SD卡和FRAM复用SPI口
	 PCSB1_CS	106	SD卡和FRAM复用SPI口
	 PCSB3_MISO	108	SD卡和FRAM复用SPI口
	 * 
	 * */
	SPIC_PORT_SCK = 109,	//SD卡和FRAM复用SPI口
	SPIC_PORT_MOSI = 107,	//SD卡和FRAM复用SPI口
	SPIC_PORT_CS = 106,	//SD卡和FRAM复用SPI口
	SPIC_PORT_MISO = 108	//SD卡和FRAM复用SPI口
};
//#define IO_CTL_LED5  145
//#define IO_CTL_LED4	 144
//#define IO_CTL_LED3	 143
//#define IO_CTL_LED2	 142
//#define IO_CTL_LED1	 141
//#define IO_CTL_PRECHARGE	 126
//#define IO_CTL_DISCHARGE_NEGATIVE	 125
//#define IO_CTL_DISCHARGE_POSITIVE	 124
//#define IO_CTL_CHARGE	 123
//#define IO_CTL_INS_CTRL_V_NEGATIVE	 122 //絕緣電阻
//#define IO_CTL_INS_CTRL_V_POSITIVE	 121 //劇院電阻
//#define IO_CTL_BUZZ	 139
//#define IO_CTL_HEAT	 128
//#define IO_CTL_FANS	 127
//
//#define IO_STATUS_CP_C	 138
//#define IO_STATUS_ON	 135
//#define IO_STATUS_ACC	 134
//#define IO_STATUS_CC2	 133
//#define IO_STATUS_PRECHARGE	 117
//#define IO_STATUS_CHARGE	 116
//#define IO_STATUS_DISCHARGE_POSITIVE	 115
//#define IO_STATUS_DISCHARGE_NEGATIVE	 114
//
//
//#define IO_ISR_CP_T	 137  //PWM
//#define IO_SD_WP	 130
//#define IO_SD_CD	 129
//#define IO_FRAM_WP	 120
///*
// CC	ADC 5	交流充电机接口状态检测（需将检测到的电压值换算成电阻值）
// ADC_YC	ADC 4	预充电压检测
// ADC_CU2	ADC 3	霍尔传感器电流检测（充电）
// ADC_CU1	ADC 2	霍尔传感器电流检测（放电）
// INS_V-	ADC 1	绝缘电阻检测（电池组负极对地绝缘电阻）
// INS_V+	ADC 0	绝缘电阻检测（电池组正极对地绝缘电阻）
// */
//#define ADC_PORT_INS_P 0
//#define ADC_PORT_INS_N 1
//#define ADC_PORT_CURRENT_DISCHARGE 2
//#define ADC_PORT_CURRENT_CHARGE 3
//#define ADC_PORT_PRECHARGE 4
//#define ADC_PORT_ACCIN 5  // AC charger insert check
///*
// MBM_SCK	SPI GPIO102	LTC6804通讯
// MBM_CS	SPI GPIO105	LTC6804通讯
// MBM_MISO	SPI GPIO103	LTC6804通讯
// MBM_MOSI	SPI GPIO104	LTC6804通讯
// * 
// * */
//#define SPIB_PORT_SCK	102
//#define SPIB_PORT_CS	105
//#define SPIB_PORT_MISO	103//179     //
//#define SPIB_PORT_MOSI	104
//
///*
// PCSB4_SCK	109	SD卡和FRAM复用SPI口
// PCSB2_MOSI	107	SD卡和FRAM复用SPI口
// PCSB1_CS	106	SD卡和FRAM复用SPI口
// PCSB3_MISO	108	SD卡和FRAM复用SPI口
// * 
// * */
//#define SPIC_PORT_SCK	109	//SD卡和FRAM复用SPI口
//#define SPIC_PORT_MOSI	107	//SD卡和FRAM复用SPI口
//#define SPIC_PORT_CS	106	//SD卡和FRAM复用SPI口
//#define SPIC_PORT_MISO	108	//SD卡和FRAM复用SPI口
enum GPIO_IDS
{
	ID_IO_CTL_LED5 = 0,
	ID_IO_CTL_LED4,
	ID_IO_CTL_LED3,
	ID_IO_CTL_LED2,
	ID_IO_CTL_LED1,
	ID_IO_CTL_PRECHARGE, // = 5
	ID_IO_CTL_DISCHARGE_NEGATIVE,
	ID_IO_CTL_DISCHARGE_POSITIVE,
	ID_IO_CTL_CHARGE,
	ID_IO_CTL_INS_CTRL_V_NEGATIVE,
	ID_IO_CTL_INS_CTRL_V_POSITIVE, // = 10
	ID_IO_CTL_BUZZ,
	ID_IO_CTL_HEAT, 
	ID_IO_CTL_FANS,
	ID_IO_STATUS_CP_C,
	ID_IO_STATUS_ON, // = 15,
	ID_IO_STATUS_ACC,
	ID_IO_STATUS_CC2,
	ID_IO_STATUS_PRECHARGE,
	ID_IO_STATUS_CHARGE,
	ID_IO_STATUS_DISCHARGE_POSITIVE,
	ID_IO_STATUS_DISCHARGE_NEGATIVE,
	ID_IO_BMS_END
};
enum ADC_PORTS
{

	ID_ADC_PORT_INS_P = 0,
	ID_ADC_PORT_INS_N = 1,
	ID_ADC_PORT_CURRENT_DISCHARGE = 2,
	ID_ADC_PORT_CURRENT_CHARGE = 3,
	ID_ADC_PORT_PRECHARGE = 4,
	ID_ADC_PORT_ACCIN = 5,  // AC charger insert check	
	ID_ADC_TOTAL
};

static const UINT8 gpioPorts[] =
{ IO_CTL_LED5, IO_CTL_LED4, IO_CTL_LED3, IO_CTL_LED2, IO_CTL_LED1,
		IO_CTL_PRECHARGE, IO_CTL_DISCHARGE_NEGATIVE, IO_CTL_DISCHARGE_POSITIVE,
		IO_CTL_CHARGE, IO_CTL_INS_CTRL_V_NEGATIVE, IO_CTL_INS_CTRL_V_POSITIVE,
		IO_CTL_BUZZ, IO_CTL_HEAT, IO_CTL_FANS, IO_STATUS_CP_C, IO_STATUS_ON,
		IO_STATUS_ACC, IO_STATUS_CC2, IO_STATUS_PRECHARGE, IO_STATUS_CHARGE,
		IO_STATUS_DISCHARGE_POSITIVE, IO_STATUS_DISCHARGE_NEGATIVE };

static const UINT8 g_in_port[] =
{ IO_STATUS_CP_C, IO_STATUS_ON, IO_STATUS_ACC, IO_STATUS_CC2,
		IO_STATUS_PRECHARGE, IO_STATUS_CHARGE, IO_STATUS_DISCHARGE_POSITIVE,
		IO_STATUS_DISCHARGE_NEGATIVE };

static const UINT8 g_out_port[] =
{ IO_CTL_LED5, IO_CTL_LED4, IO_CTL_LED3, IO_CTL_LED2, IO_CTL_LED1,
		IO_CTL_PRECHARGE, IO_CTL_DISCHARGE_NEGATIVE, IO_CTL_DISCHARGE_POSITIVE,
		IO_CTL_CHARGE, IO_CTL_INS_CTRL_V_NEGATIVE, IO_CTL_INS_CTRL_V_POSITIVE,
		IO_CTL_BUZZ, IO_CTL_HEAT, IO_CTL_FANS };

static const UINT8 g_adc_port[ID_ADC_TOTAL] = 
{
		ADC_PORT_INS_P ,
		ADC_PORT_INS_N ,
		ADC_PORT_CURRENT_DISCHARGE ,
		ADC_PORT_CURRENT_CHARGE ,
		ADC_PORT_PRECHARGE ,
		ADC_PORT_ACCIN ,  // AC charger insert check
};

#endif
