################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
ASM_UPPER_SRCS_QUOTED := 
OBJ_SRCS_OS_FORMAT := 
CXX_SRCS := 
C++_SRCS_OS_FORMAT := 
CXX_SRCS_QUOTED := 
TODISASSEMBLE_SRCS_OS_FORMAT := 
S_UPPER_SRCS_QUOTED := 
TODISASSEMBLE_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS_QUOTED := 
O_SRCS_OS_FORMAT := 
TOPREPROCESS_SRCS := 
C_SRCS_QUOTED := 
CC_SRCS_QUOTED := 
S_SRCS_OS_FORMAT := 
C_UPPER_SRCS := 
O_SRCS_QUOTED := 
C_UPPER_SRCS_QUOTED := 
OBJ_SRCS := 
ASM_SRCS := 
TOPREPROCESS_SRCS_OS_FORMAT := 
ASM_UPPER_SRCS := 
C++_SRCS := 
ASM_SRCS_OS_FORMAT := 
CXX_SRCS_OS_FORMAT := 
C_SRCS := 
CPP_SRCS_OS_FORMAT := 
C++_SRCS_QUOTED := 
S_SRCS := 
CPP_SRCS_QUOTED := 
ASM_SRCS_QUOTED := 
C_UPPER_SRCS_OS_FORMAT := 
CC_SRCS_OS_FORMAT := 
S_SRCS_QUOTED := 
TOPREPROCESS_SRCS_QUOTED := 
ASM_UPPER_SRCS_OS_FORMAT := 
C_SRCS_OS_FORMAT := 
TODISASSEMBLE_SRCS_QUOTED := 
S_UPPER_SRCS_OS_FORMAT := 
CC_SRCS := 
ASM_DEPS_OS_FORMAT := 
S_DEPS_QUOTED := 
OBJS := 
EXECUTABLES_OS_FORMAT := 
STATICLIB_OS_FORMAT := 
STATICLIB_QUOTED := 
S_DEPS := 
S_UPPER_DEPS := 
STATICLIB := 
ASM_DEPS := 
CC_DEPS := 
OBJS_QUOTED := 
CPP_DEPS_QUOTED := 
CC_DEPS_QUOTED := 
CPP_DEPS := 
S_UPPER_DEPS_QUOTED := 
EXECUTABLES := 
C++_DEPS_OS_FORMAT := 
CXX_DEPS_QUOTED := 
C_DEPS := 
CXX_DEPS_OS_FORMAT := 
C_UPPER_DEPS_OS_FORMAT := 
CC_DEPS_OS_FORMAT := 
ASM_DEPS_QUOTED := 
S_UPPER_DEPS_OS_FORMAT := 
S_DEPS_OS_FORMAT := 
CXX_DEPS := 
C++_DEPS := 
ASM_UPPER_DEPS_QUOTED := 
C_UPPER_DEPS_QUOTED := 
CPP_DEPS_OS_FORMAT := 
ASM_UPPER_DEPS := 
C++_DEPS_QUOTED := 
ASM_UPPER_DEPS_OS_FORMAT := 
C_DEPS_OS_FORMAT := 
EXECUTABLES_QUOTED := 
C_UPPER_DEPS := 
OBJS_OS_FORMAT := 
C_DEPS_QUOTED := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Sources \
Project_Settings/Startup_Code \
Master/driver/uart \
Master/driver/timer \
Master/driver/spi \
Master/driver/rtc \
Master/driver/pll \
Master/driver/intc \
Master/driver/eprom \
Master/driver/adc \
Master/driver/LTC68042 \
Master/driver/Gpio \
Master/driver/CAN \
Master/app/voltage \
Master/app/temp \
Master/app/soh \
Master/app/soc \
Master/app/soc/soc \
Master/app/selftest \
Master/app/public \
Master/app/protocol \
Master/app/middleLayer \
Master/app/mgclib \
Master/app/insulation_resistance \
Master/app/current \
Master/app/ctl \
Master/app/banlance_battery \

